### PR TITLE
Allow disabling the welcome banner.

### PR DESCRIPTION
**Pull request by james-w**
Also print the welcome banner and update messages to stderr
so they don't interfere with any data stream on stdout.

### CODE REVIEW

**Comment by james-w** [comment]
This works for me:

    $ docker run --rm -i  -e BITNAMI_APP_NAME=asd f279b0e8e401 echo "a" | wc

      *** Welcome to the asd image ***
      *** Brought to you by Bitnami ***
      *** More information: https://github.com/bitnami/bitnami-docker-asd ***
      *** Issues: https://github.com/bitnami/bitnami-docker-asd/issues ***
    
          1       1       2

    $ docker run --rm -i -e DISABLE_WELCOME_MESSAGE=1 -e BITNAMI_APP_NAME=asd f279b0e8e401 echo "a" | wc
          1       1       2

**Comment by sameersbn** [comment]
@james-w I am seeing very different results

```bash
$ docker run -it -e BITNAMI_APP_NAME=asd --rm cb0f9c0f4d8a echo "a" | wc
      7      24     227
```

```bash
$ docker run --rm -i -e DISABLE_WELCOME_MESSAGE=1 -e BITNAMI_APP_NAME=asd cb0f9c0f4d8a echo "a" | wc
      1       1       2
```

There seems to be a a difference in the way the output on the stderr is handled by docker

Setup:
  Host OS: Ubuntu 16.04
  Docker Version: 1.12.6

```bash
$ docker info
Containers: 19
 Running: 10
 Paused: 0
 Stopped: 9
Images: 305
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 205
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: MacBookPro
ID: PD5B:VKQF:F6YM:YJXT:KN7W:3N5T:BZLD:E2FK:UGZG:4P4V:E4XZ:7FDT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sameersbn
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by james-w** [comment]
The difference is `-t`, it makes docker merge the streams.

Try it without and you should see a difference.

**Comment by james-w** [comment]
Fixes #82

**Comment by prydonius** [comment]
@james-w can confirm that the issue is pty. Thanks!

**Pull request merged**
