### PR TITLE
Setup Travis test and release builds

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by prydonius** [comment]
@sameersbn building all the images makes this pretty slow, any ideas for optimisations? We could check what files have changed and only run the tests for the Dockerfiles that have changed?

**Comment by prydonius** [comment]
Sigh, it looks like the docker version in CircleCI is too old to reference content shas

**Comment by prydonius** [comment]
We can use Travis for these builds, which has Docker 1.12

**Comment by sameersbn** [comment]
> Sigh, it looks like the docker version in CircleCI is too old to reference content shas

damn!

**Comment by sameersbn** [comment]
LGTM :+1:

**Pull request merged**
